### PR TITLE
fix: android strerror

### PR DESCRIPTION
**Pull request by bmahlbrand**
Fix for #52

### CODE REVIEW

**Comment by paulo-coutinho** [comment]
I will be merged?

**Comment by talregev** [comment]
@fpagliughi, I updated the port in vcpkg.
https://github.com/microsoft/vcpkg/pull/19769
They are waiting for your approval. 
If you approve this change (even before the pull request approve), they will approve my PR. 
Then in the next release, I will remove the patch (if needed).

**Comment by talregev** [comment]
@fpagliughi  any news?

**Comment by fpagliughi** [comment]
Yes, sorry. I've had little time to work on open source this past year. I'll get this in a quick release of some minor updates now.

**Comment by paulo-coutinho** [comment]
Nice, no problem. Thanks.

**Pull request merged**
