### PR TITLE
Refactoring the CMakeFiles.txt files

### LINKED ISSUE #45: The cmake doesn't generate config file to be included as a 3th party project
I am developing a library, which uses come 3rd party libraries including this one. For the other libraries, I was able to include them using the following `CMakeLists.txt` code:
```cmake
find_package(package_name REQUIRED)
target_link_libraries(my_target_name PRIVATE package_name::package_name)
```
but for this one, it says the following:

> Could not find a package configuration file provided by "sockpp-static" with any of the following names:
> sockpp-staticConfig.cmake
> sockpp-static-config.cmake

### PR DESCRIPTION
**Pull request by arsdever**
Fixes #45

### CODE REVIEW

**Comment by fpagliughi** [comment]
Thanks for the PR! I've been meaning to get to the export config stuff for a while now, but just haven't found the time. This looks awesome/simpler if it works across all the different targets.

What platforms did you test this on?  

In Windows, if you turn on both static and shared builds, how does it deal with naming the static lib vs the import lib for the DLL, since they both use the same ".lib" extension?

**Comment by arsdever** [comment]
> What platforms did you test this on?

I tested only on Windows 10.

> In Windows, if you turn on both static and shared builds, how does it deal with naming the static lib vs the import lib for the DLL, since they both use the same ".lib" extension?

I didn't think about this scenario. BTW is the option useful to build for both `shared` and `static` targets at the same time?

- If it is, then I have to think about that
- If not, then I will remove one of the options and say 
  > If you choose `STATIC` than it builds a static library, else it builds a dynamic library.

Does this make sense?

**Comment by fpagliughi** [comment]
The way it is currently implemented, it can build both shared and static, if you ask for both. That's why it specifically named the static library differently with the "-static" appended to the base name.

Note that this "-static" name addition is only required on Windows. On *nix systems, it can build the static lib as ".a", and the shared lib as ".so"

**Comment by fpagliughi** [comment]
Note, in the original CMake file, it specifically renamed the output for the static build so that it would have the same base name as the shared library (no "-static"):
```
	# Let the archive use the same name as the shared library
	if(UNIX)
		set_target_properties(${SOCKPP_STATIC} PROPERTIES OUTPUT_NAME ${SOCKPP})
	endif()
```
I'm not fixed on doing things one way or another, but I would want to be careful about breaking people's builds or removing features if we didn't have to. Most people would know if they want one or the other shared/static, but if you're doing a generic build for a distribution, you probably want to build both versions and let individual users/projects decide which to link to.

**Comment by arsdever** [comment]
Yes, I understand, but it doesn't answer my question. What is the use-case to build both (shared and static) libraries at the same time?

**Comment by fpagliughi** [comment]
First, I agree completely, that what you want to add is really important. I want to get it in there, too.

> What is the use-case to build both (shared and static) libraries at the same time?

I assume the most common reason would be to have both versions on a shared computer where different users or different applications have need of one version of the library or the other. I have multiple applications using this library, and though most use the shared library, some (by customer dictate) link to the static lib. So it's convenient to have both installed.

But if you're asking whether it would just be easier to have a user run the build twice to get the shared library one time and the static library the next, then I'm not sure. Can that be done without the install overwriting anything important?

But the main point I was making is that it currently does both, which is why I did it this way rather than just using `BUILD_SHARED_LIBS`. I'm not sure what people currently need, one way or another, but I'd hate to take something away if people already rely on it. 

I think what you want to add is really important. But it would be cool to figure out if there is a way to add it without taking away something else.

**Comment by arsdever** [comment]
You completely answered my question. Then, let me think about solution. I will update PR as soon as I find it out.

**Comment by fpagliughi** [comment]
Yes, apologies that I'm a bit of a novice with CMake, so I don't have a ready solution either, but hopefully we can figure out something easy enough. And I appreciate your work on this.

**Comment by arsdever** [comment]
Here I'm listing the versions I think are applicable (this comment will be modified and updated later)

1. Providing 2 targets: `sockpp-shared` and `sockpp-static` for `shared` and `static` libraries respectively. If the user wants to link to `shared`, he/she must `cmake` the project according to the needs and then use `find_package(sockpp-<libtype>)` as required.

**Comment by arsdever** [comment]
BTW I'm also new to CMake and find this very important to also learn CMake ;)

**Comment by arsdever** [comment]
@fpagliughi Can you please explain why it prefers shared lib to take place into testing? https://github.com/fpagliughi/sockpp/blob/93855d54e78ea2684abe0f75caf4dbdf98bffcab/CMakeLists.txt#L176-L180

**Comment by fpagliughi** [comment]
It prefers the shared library for testing because I was primarily using the shared library for my personal deploys!  Plus shared libraries tend to have a few more quirks than just linking in a static library.

But it's not something I fell very strongly about one way or another.

**Comment by arsdever** [comment]
I'm quite done with the solution I mentioned above. Just to clarify. Is it that I change the shared library name to `sockpp-shared` instead of `sockpp`? It isn't critical for me but makes sense to the customer to explicitly mention in their project whether they want a `shared` or `static` library. How do you think?

**Comment by arsdever** [comment]
Actually, after the last comment, I lost all the changes I made and I'm happy about that because I was in the wrong way. 😄 Currently, I wonder why we `install` the examples? Do we need them to be `installed`? I'm removing their `install` action and preparing the new PR. If it is needed to leave them please inform me.

**Comment by fpagliughi** [comment]
I would think to keep the shared library name as just "sockpp".  Also remember that _both_ libraries install as "sockpp" on non-Windows targets. I certainly don't want the weirdness of Windows to affect *nix systems, in any way, if possible. :-)

As for the examples, yes they should be installed if the user requests them to be built! 
(But they're not built, by default).

**Comment by arsdever** [comment]
> As for the examples, yes they should be installed if the user requests them to be built!
> (But they're not built, by default).
I mean the building is, of course, a must. But what about installing? Why is it needed? Isn't it needed only when you're going to include the package into your project? Or I have some misunderstanding here.

**Comment by fpagliughi** [comment]
Well remember that you have a specific view of the library!  You're thinking of it in terms of just a subproject to be included in a build of your own application. In that case, you would not want or ask for the examples to be built. And they would not be installed.

But if, for whatever reason, you want to build and install the project independently, to be shared amongst many applications, and you ask for the examples to be built, you would expect them to also be installed. In most cases, the build directory is temporary, and everything in it will be erased after the install completes. So, whatever you asked to be built, you would expect to be installed. Otherwise, why would you ask for it to be built?

**Comment by arsdever** [comment]
Any comments on the PR update?

**Comment by fpagliughi** [comment]
Apologies that I'm really busy on another open source project that I need to get out in the next week or so, then I can take a closer look at this.

**Comment by arsdever** [comment]
No worries. By the time I continue to experience with the lib. I will make some touches if needed before merging.

**Comment by fpagliughi** [comment]
Hey @arsdever! Sorry it took me two years to get to this, but I'm finally back to doing some C++ work and getting a little more comfortable with CMake. I had to do some manual merging since the fork is gone, but I think I got everything. I put it all in a `cmake-refactor` to play with it a little. So far, it looks really good.

Thanks again,

**Pull request closed without merging**
