### PR TITLE
Fixed broken compilation of examples on Windows/msvs2015u3

### LINKED ISSUE #42: Some xamples won't compile on Windows (VS2015 with update3)
Hello.
I ran into a couple of issues trying to build examples with MSVS2015 update3 on Windows:

1. Error in the tcpechotest.cpp:

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\random(2387): error C2338: invalid template argument for uniform_int_distribution
F:\dump\sockpp\examples\tcp\tcpechotest.cpp(92): note: see reference to class template instantiation 'std::uniform_int_distribution<char>' being compiled
```
This is because the template parameter of std::uniform_int_distribution must be either: `int`, `short`, `long`, `long long` or their unsigned counterpart. Please see `Template parameters` section here: [std::uniform_int_distribution](https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution)

2. Error in the udpechosvr.cpp:

```
F:\dump\sockpp\examples\udp\udpechosvr.cpp(75): error C2666: 'sockpp::datagram_socket_tmpl<sockpp::inet_address>::send_to': 2 overloads have similar conversions
F:\dump\sockpp\include\sockpp/datagram_socket.h(355): note: could be 'ssize_t sockpp::datagram_socket_tmpl<sockpp::inet_address>::send_to(const void *,std::size_t,const ADDR &)'
<...>
F:\dump\sockpp\include\sockpp/datagram_socket.h(345): note: or       'ssize_t sockpp::datagram_socket_tmpl<sockpp::inet_address>::send_to(const std::string &,int,const ADDR &)'
```
You can see the full error text for the 2nd issue here: https://gist.github.com/tsilia/6c9959ad0393a211970160c598a7cd41

### PR DESCRIPTION
**Pull request by tsilia**
Fixes #42

### CODE REVIEW

**Comment by tsilia** [comment]
Hello @fpagliughi 

I'd also recommend to change signatures of `datagram_socket_tmpl::send_to` and `datagram_socket_tmpl::recv_from` so that they accept `uint8_t*` rather than `void*`. IMO, this would be more type-safe because this way it requires an explicit cast to `uint8_t*` when calling those methods, instead of relying on silent automatic cast to `void*`. Besides, `void*` looks more C-way than C++ 😉

But since this changes API and potentially breaks code (I checked that examples do compile though), I'm only suggesting that in a comment rather than in a PR. I'll update the PR if you're OK with that.

**Comment by fpagliughi** [comment]
Cool. Thanks. I'll get this tested over the next few days, but it doesn't look like anything that would cause a problem. 

As for changing the signature of the send/recv functions, no, I don't think that's worth doing a breaking change. A lot of people would then need to update their projects to adapt the change (myself included) and not really get anything for it. Plus, when I've tried this sort of thing in the past, it's created a lot of problems with string data. Since different systems/compilers treat characters as signed or unsigned, it doesn't always port well.

**Comment by fpagliughi** [comment]
OK, a quick look, and it appears that `uniform_int_distribution<char>` is definitely not supported by the C++ standard. So it's good to get that out of there.

But as for using `std::array<>` as a read buffer, I am unconvinced. Since the `size()` of an array is fixed, it doesn't actually tell you the number of valid items in the array, but rather just the capacity. I think it would be a bad example to use array.

This library popped out of a bigger one that had a bunch of different type definitions, including an I/O `buffer` class that could be returned from a read() operation. In that case it would be properly sized from the read. Something like that would be better and perhaps more "C++", but I think that's a little beyond the scope of this library.

**Comment by tsilia** [comment]
The std::array is just a thin wrapper over a C-ctyle array, but no problem, I've updated the PR. The cast to `void*` is there in order to avoid ambiguity (the details are in #42).

**Comment by fpagliughi** [comment]
Oops. I missed that the casting was required for MSVS. OK, we'll get that fixed.

**Pull request closed without merging**
